### PR TITLE
CPU socket count reporting correction

### PR DESCRIPTION
**Pull request by NuxRo**
CPU socket count reporting correction
From https://github.com/MissionCriticalCloud/cosmic-plugin-hypervisor-kvm/pull/16

### CODE REVIEW

**Comment by karuturi** [comment]
@NuxRo you need to create a PR on apache/cloudstack. This one is on your private fork NuxRo/cloudstack

**Comment by remibergsma** [comment]
Hi @NuxRo, Almost there! When you go here: https://github.com/apache/cloudstack/compare?expand=1 you can create a new PR against Apache CloudStack. Be sure to select your branch `kvm-numa-cpu-reporting` and make the PR against `4.7` I'd say so it will eventually be fixed in newer versions of 4.7, 4.8 and 4.9 (should the be released). 
Although not sure which branch you made the PR against. If it's master, send it to master.

**Comment by NuxRo** [comment]
Thanks guys, silly me.

Remi, when I go to that URL my branch is not available. I'll try some other way.

**Comment by NuxRo** [comment]
Ok, managed to create a pull request against master. Against 4.7 there were a lot of changed files, probably I was doing something wrong.

https://github.com/apache/cloudstack/pull/1520

**Pull request merged**
